---
# tasks file for Debian.yml

# Setup the required repositories
- name: (Ubuntu) Make sure the universe repo is enabled
  tags: [ 'ps::install' ]
  # It is better to use add-apt-repository rather than the apt_repository
  # module from Ansible.  This command will NOT duplicate an already existing
  # universe repo setup using a mirror.
  shell: LANGUAGE=C add-apt-repository universe
  when: ansible_distribution == "Ubuntu"
  register: universe_output
  changed_when: universe_output.stdout != "'universe' distribution component is already enabled for all sources."

- name: (Debian) Import perfSONAR repository signing key - {{ perfsonar_release }}
  tags: [ 'ps::install' ]
  apt_key:
    url: http://downloads.perfsonar.net/debian/perfsonar-{{ perfsonar_release }}.gpg.key
    state: present

- name: Remove previously configured repositories
  tags: [ 'ps::install' ]
  file:
    path: /etc/apt/sources.list.d/downloads_perfsonar_net_debian.list
    state: absent

- name: (Debian) Add perfSONAR repository - {{ perfsonar_release }}
  tags: [ 'ps::install' ]
  apt_repository:
    repo: deb http://downloads.perfsonar.net/debian/ perfsonar-{{ perfsonar_release }} main
    state: present

- name: (Debian) Install system updates
  tags: [ 'ps::install' ]
  apt:
    upgrade: dist
    update_cache: yes
  ignore_errors: True
  when: perfsonar_os_update == True
